databases:
  - name: railway_reservation_system
    databaseName: railway_reservation_system_production
    user: railway_reservation_system
    plan: free

services:
  - type: web
    name: railway_reservation_system
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railway_reservation_system
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
<<<<<<< HEAD
        value: 2
=======
        value: 2 
>>>>>>> c959316851985c340897361f8fe2a2beb57ae262
